"""add signup link table

Revision ID: ae28a71016ac
Revises: 
Create Date: 2024-11-23 07:18:35.650406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae28a71016ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('state', sa.String(length=20), nullable=False))
    op.drop_column('hospitals', 'hospital_admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('hospital_admin_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('hospitals', 'state')
    # ### end Alembic commands ###
